### PR TITLE
Fix cplcf->conf->purge_all causing segmentation fault

### PR DESCRIPTION
**Pull request by machadovilaca**
Segmentation Fault when trying to purge all the content from nginx cache.
cplcf->conf value was 0x0.
Fixed by changing cplcf structure field accessed to cplcf->fastcgi.purge_all.

### CODE REVIEW

**Comment by denji** [comment]
@machadovilaca `ngx_http_proxy_cache_purge_handler` -> `cplcf->fastcgi.purge_all`?

**Comment by machadovilaca** [comment]
ohhh...I was fixing the error specifically for a fastcgi cache configuration and I generalized the solution for all different types. I will review the code and correct it accordingly.

**Comment by machadovilaca** [comment]
Ok, I reviewed the code, and changed proxy,scgi and uwsgi. BTW in ngx_http_cache_purge_handler function I was not able to avoid using else ifs to fix my segmentation fault error.

**Comment by denji** [comment]
Resolved nginx-modules/ngx_cache_purge#9

**Pull request closed without merging**
